// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Camera.proto

#include "Camera.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace hal {
PROTOBUF_CONSTEXPR CameraMsg::CameraMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.image_)*/{}
  , /*decltype(_impl_.device_time_)*/0
  , /*decltype(_impl_.system_time_)*/0
  , /*decltype(_impl_.id_)*/0} {}
struct CameraMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CameraMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CameraMsgDefaultTypeInternal() {}
  union {
    CameraMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CameraMsgDefaultTypeInternal _CameraMsg_default_instance_;
}  // namespace hal
static ::_pb::Metadata file_level_metadata_Camera_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Camera_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Camera_2eproto = nullptr;

const uint32_t TableStruct_Camera_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::hal::CameraMsg, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hal::CameraMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hal::CameraMsg, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::hal::CameraMsg, _impl_.device_time_),
  PROTOBUF_FIELD_OFFSET(::hal::CameraMsg, _impl_.image_),
  PROTOBUF_FIELD_OFFSET(::hal::CameraMsg, _impl_.system_time_),
  2,
  0,
  ~0u,
  1,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, -1, sizeof(::hal::CameraMsg)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::hal::_CameraMsg_default_instance_._instance,
};

const char descriptor_table_protodef_Camera_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014Camera.proto\022\003hal\032\013Image.proto\"_\n\tCame"
  "raMsg\022\n\n\002id\030\001 \001(\005\022\023\n\013device_time\030\002 \001(\001\022\034"
  "\n\005image\030\003 \003(\0132\r.hal.ImageMsg\022\023\n\013system_t"
  "ime\030\004 \001(\001"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Camera_2eproto_deps[1] = {
  &::descriptor_table_Image_2eproto,
};
static ::_pbi::once_flag descriptor_table_Camera_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Camera_2eproto = {
    false, false, 129, descriptor_table_protodef_Camera_2eproto,
    "Camera.proto",
    &descriptor_table_Camera_2eproto_once, descriptor_table_Camera_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_Camera_2eproto::offsets,
    file_level_metadata_Camera_2eproto, file_level_enum_descriptors_Camera_2eproto,
    file_level_service_descriptors_Camera_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Camera_2eproto_getter() {
  return &descriptor_table_Camera_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Camera_2eproto(&descriptor_table_Camera_2eproto);
namespace hal {

// ===================================================================

class CameraMsg::_Internal {
 public:
  using HasBits = decltype(std::declval<CameraMsg>()._impl_._has_bits_);
  static void set_has_id(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_device_time(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_system_time(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

void CameraMsg::clear_image() {
  _impl_.image_.Clear();
}
CameraMsg::CameraMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hal.CameraMsg)
}
CameraMsg::CameraMsg(const CameraMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CameraMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.image_){from._impl_.image_}
    , decltype(_impl_.device_time_){}
    , decltype(_impl_.system_time_){}
    , decltype(_impl_.id_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.device_time_, &from._impl_.device_time_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.id_) -
    reinterpret_cast<char*>(&_impl_.device_time_)) + sizeof(_impl_.id_));
  // @@protoc_insertion_point(copy_constructor:hal.CameraMsg)
}

inline void CameraMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.image_){arena}
    , decltype(_impl_.device_time_){0}
    , decltype(_impl_.system_time_){0}
    , decltype(_impl_.id_){0}
  };
}

CameraMsg::~CameraMsg() {
  // @@protoc_insertion_point(destructor:hal.CameraMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CameraMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.image_.~RepeatedPtrField();
}

void CameraMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CameraMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:hal.CameraMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.image_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&_impl_.device_time_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.id_) -
        reinterpret_cast<char*>(&_impl_.device_time_)) + sizeof(_impl_.id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CameraMsg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_id(&has_bits);
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional double device_time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _Internal::set_has_device_time(&has_bits);
          _impl_.device_time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated .hal.ImageMsg image = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_image(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // optional double system_time = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _Internal::set_has_system_time(&has_bits);
          _impl_.system_time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CameraMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hal.CameraMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 id = 1;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // optional double device_time = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_device_time(), target);
  }

  // repeated .hal.ImageMsg image = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_image_size()); i < n; i++) {
    const auto& repfield = this->_internal_image(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  // optional double system_time = 4;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_system_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hal.CameraMsg)
  return target;
}

size_t CameraMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hal.CameraMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .hal.ImageMsg image = 3;
  total_size += 1UL * this->_internal_image_size();
  for (const auto& msg : this->_impl_.image_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional double device_time = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 8;
    }

    // optional double system_time = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 8;
    }

    // optional int32 id = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CameraMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CameraMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CameraMsg::GetClassData() const { return &_class_data_; }


void CameraMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CameraMsg*>(&to_msg);
  auto& from = static_cast<const CameraMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hal.CameraMsg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.image_.MergeFrom(from._impl_.image_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.device_time_ = from._impl_.device_time_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.system_time_ = from._impl_.system_time_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.id_ = from._impl_.id_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CameraMsg::CopyFrom(const CameraMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hal.CameraMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CameraMsg::IsInitialized() const {
  return true;
}

void CameraMsg::InternalSwap(CameraMsg* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.image_.InternalSwap(&other->_impl_.image_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CameraMsg, _impl_.id_)
      + sizeof(CameraMsg::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(CameraMsg, _impl_.device_time_)>(
          reinterpret_cast<char*>(&_impl_.device_time_),
          reinterpret_cast<char*>(&other->_impl_.device_time_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CameraMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Camera_2eproto_getter, &descriptor_table_Camera_2eproto_once,
      file_level_metadata_Camera_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace hal
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::hal::CameraMsg*
Arena::CreateMaybeMessage< ::hal::CameraMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hal::CameraMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
